user_log = logging.getLogger("user_log")
bot_log = logging.getLogger("bot_log")

fh_user = logging.FileHandler("user.log", mode="a+")
fh_user.setLevel(logging.INFO) 
formatter = logging.Formatter('%(asctime)s - %(name)s - %(message)s')
fh_user.setFormatter(formatter)
user_log.addHandler(fh_user)
user_log.setLevel(logging.INFO)

fh_bot = logging.FileHandler("bot.log", mode="a+")
fh_bot.setLevel(logging.INFO)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(message)s')
fh_bot.setFormatter(formatter)
bot_log.addHandler(fh_bot)
bot_log.setLevel(logging.INFO)
